SELECT (SELECT CITY FROM STATION  WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1), MIN(LENGTH(CITY)) FROM STATION;
SELECT (SELECT CITY FROM STATION  WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION) ORDER BY CITY LIMIT 1), MAX(LENGTH(CITY)) FROM STATION;


